from pathlib import Path
import json
S={'type':'string'}
N={'type':'null'}
B={'type':'boolean'}
I={'type':'integer','minimum':0}
H={'type':'string','pattern':'^[a-f0-9]{64}$'}
UUID={'type':'string','format':'uuid','pattern':'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'}
D={'type':'string','format':'date-time','pattern':'Z$'}
def en(*values):return {'enum':list(values)}
def arr(t,max=100):return {'type':'array','items':t,'maxItems':max}
def obj(props,req=None):return {'type':'object','properties':props,'required':list(props) if req is None else req,'additionalProperties':False}
def nullable(t):return {'anyOf':[t,N]}
def anyJson():return {'anyOf':[{'type':x} for x in ['object','array','string','number','boolean','null']]}
flag=en(True,False,'unknown')
path={'type':'string','minLength':1,'maxLength':2000,'pattern':'^(?!/)(?!.*(?:^|/)\\.\\.(?:/|$))[^\\x00-\\x1f\\\\]+$'}
subject=obj({'component':S,'path':path,'bundleKey':S,'dependencyId':obj({'manager':en('spm','pods','local'),'name':S,'version':S,'bundleKey':S}),'permissionKey':S,'locale':S},['component'])
scopekey=obj({'project':path,'targetId':S,'configuration':S,'sdk':en('iphoneos','iphonesimulator'),'arch':en('arm64','x86_64','unknown')})
features=obj({**{k:flag for k in ['accountCreation','loginRequired','thirdPartyDataSharing','thirdPartyAI','tracking','paidApp','socialNetworking','kidsCategory']},'authProviders':{'anyOf':[en('unknown'),arr(en('apple','google','facebook','email','custom'))]},'productTypes':{'anyOf':[en('unknown'),arr(en('consumable','non_consumable','auto_renewable','non_renewing'))]},'permissions':{'anyOf':[en('unknown'),arr(en('camera','microphone','location','photos','contacts'))]}},[])
prepkeys=['ageRating','socialNetworking','appPrivacy','dpla','paidAppsAgreement','traderStatus','traderInformation']
config=obj({'schemaVersion':en('1.0.0'),'project':nullable(path),'workspace':nullable(path),'target':nullable(S),'targetId':nullable(S),'configuration':S,'sdk':en('iphoneos','iphonesimulator'),'arch':en('arm64','x86_64','unknown'),'language':en('ja','en'),'features':features,'policy':obj({'storefronts':{'anyOf':[en('unknown'),{**arr({'type':'string','pattern':'^[A-Z]{2}$'}),'minItems':1,'uniqueItems':True}]},'deviceFamilies':{'anyOf':[en('unknown'),{**arr(en('iphone','ipad')),'minItems':1,'uniqueItems':True}]},'distributionChannel':en('app_store','testflight','enterprise','ad_hoc','development','alternative','unknown'),'plannedSubmissionDate':nullable({'type':'string','format':'date'}),'timeZone':S},[]),'authProviderDetails':nullable(S),'reviewAccess':obj({'method':en('demo_account','demo_mode','none','unknown'),'prepared':flag,'note':nullable(S)},[]),'reviewNotesPrepared':flag,'privacyPolicyURL':nullable({'type':'string','format':'uri','pattern':'^https?://'}),'reportedBuild':nullable(obj({'xcodeVersion':S,'sdkVersion':S,'buildId':S,'verifiedAt':D,'platform':en('ios','ipados'),'reporter':nullable(S)},['xcodeVersion','sdkVersion','buildId','verifiedAt'])),'submissionPreparation':obj({k:flag for k in prepkeys},[]),'preparationDetails':arr(obj({'item':en(*prepkeys),'sourceRevision':nullable(S),'verifiedAt':nullable(D),'reporter':nullable(S)})),'metadataDeclarations':nullable(obj({'socialNetworking':flag,'ageRatingReviewedAt':nullable(D),'privacy':arr(obj({'category':S,'collected':flag,'linkedToUser':flag,'usedForTracking':flag,'purposes':arr(S),'thirdParty':flag}))})),'storekitFiles':arr(path),'manualVerifications':arr(obj({'checkId':H,'scopeKey':scopekey,'method':en('device_test','sandbox_test','app_store_connect','public_url','backend_test','archive_inspection','policy_review','review_walkthrough'),'conclusion':en('pass','fail','unknown'),'observedAt':D,'semanticSnapshotHash':H,'limitations':arr(S),'reporter':nullable(S)},['checkId','scopeKey','method','conclusion','observedAt','semanticSnapshotHash','limitations'])),'exclude':arr(obj({'pathPattern':path,'reason':{'type':'string','minLength':1}})),'suppressions':arr(obj({'ruleId':S,'subjectKey':subject,'reason':{'type':'string','minLength':1},'createdAt':D,'expiresAt':{'anyOf':[D,{'type':'string','format':'date'}]}}))},['schemaVersion'])
source=obj({'sourceDocumentId':S,'title':S,'url':{'type':'string','format':'uri'},'sourceRevision':nullable(S),'verifiedAt':{'type':'string','format':'date'},'section':S})
evidence={'oneOf':[obj({'evidenceId':H,'kind':en('file'),'path':path,'fileHash':H,'lineStart':nullable({'type':'integer','minimum':1}),'lineEnd':nullable({'type':'integer','minimum':1}),'keyPath':nullable(S),'observation':S}),obj({'evidenceId':H,'kind':en('config'),'pointer':S,'valueType':S,'normalizedValue':anyJson(),'observation':S}),obj({'evidenceId':H,'kind':en('search'),'methodId':S,'inputSetHash':H,'searchedPaths':arr(path,10000),'candidateCount':I,'limitations':arr(S),'observation':S})]}
check=obj({'checkId':H,'ruleId':S,'ruleVersion':S,'subject':obj({'kind':S,'subjectKey':subject,'targetId':S}),'status':en('PASS','FAIL','NEEDS_REVIEW','NOT_APPLICABLE','UNKNOWN','ERROR'),'severity':nullable(en('HIGH','MEDIUM','LOW')),'confidence':en('HIGH','MEDIUM','LOW'),'confidenceReason':S,'title':S,'reason':S,'evidence':arr(evidence),'sources':arr(source),'provenance':en('scanner','ai','user'),'verificationLevel':en('static','ai_review','user_attestation'),'limitations':arr(S),'remediation':arr(S),'verificationSteps':arr(S)})
counts=obj({s:I for s in ['PASS','FAIL','NEEDS_REVIEW','NOT_APPLICABLE','UNKNOWN','ERROR']})
grades=obj({s:I for s in ['HIGH','MEDIUM','LOW']})
summary=obj({'riskCounts':grades,'failCounts':grades,'needsReviewCount':I,'unknownCount':I,'errorCount':I,'suppressedCount':I})
coverage=obj({'totalChecks':I,'statusCounts':counts,'executedCheckCount':I,'executedCheckRatio':nullable({'type':'number','minimum':0,'maximum':1}),'partial':B,'excludedInputCount':I,'unreadInputCount':I})
diag=obj({'code':S,'level':en('warning','error'),'stage':S,'path':nullable(S),'message':S,'affectedRuleIds':arr(S),'affectedCheckIds':arr(H,100000),'remedy':S})
file=obj({'path':path,'sizeBytes':I,'sha256':nullable(H),'role':en('project','settings','plist','entitlements','manifest','swift','dependency_lock','storekit','localization','config'),'membership':en('included','excluded','unknown','supporting'),'reason':S},['path','sizeBytes','sha256','role','membership'])
scope=obj({**scopekey['properties'],'targetName':S,'workspace':nullable(path),'platforms':arr(S),'exclusions':arr(config['properties']['exclude']['items'])})
policy=obj({'assessmentDate':D,'assessmentCalendarDate':{'type':'string','format':'date'},'timeZone':S,'plannedSubmissionDate':nullable({'type':'string','format':'date'}),'knowledgeAsOf':{'type':'string','format':'date'},'storefronts':config['properties']['policy']['properties']['storefronts'],'deviceFamilies':config['properties']['policy']['properties']['deviceFamilies'],'distributionChannel':config['properties']['policy']['properties']['distributionChannel'],'appliedRequirements':arr(S),'futureRequirements':arr(S),'unresolvedRequirements':arr(S)})
snapshot=obj({'gitHead':nullable(S),'gitDirty':nullable(B),'files':arr(file,10000),'configHash':H,'inputManifestHash':H,'semanticSnapshotHash':H})
audit=obj({'schemaVersion':en('1.0.0'),'auditId':UUID,'createdAt':D,'toolVersion':S,'rulepackVersion':S,'policyContext':policy,'scope':scope,'snapshot':snapshot,'execution':obj({'mode':en('static'),'completion':en('complete','partial'),'startedAt':D,'finishedAt':D}),'coverage':coverage,'summary':summary,'checks':arr(check,100000),'diagnostics':arr(diag,10000)})
manifest=obj({'schemaVersion':en('1.0.0'),'auditId':UUID,'auditHash':H,'inputManifestHash':H,'semanticSnapshotHash':H,'normalizedConfig':config,'configOrigin':obj({'kind':en('file','stdin','default'),'path':nullable(path),'sourceFileHash':nullable(H)}),'files':arr(file,10000),'enumerationHash':H})
execution=obj({'tool':en('claude_code','codex','cursor','other'),'model':nullable(S)})
assessment=obj({'schemaVersion':en('1.0.0'),'assessmentId':UUID,'auditId':UUID,'auditHash':H,'inputManifestHash':H,'createdAt':D,'execution':execution,'reviews':arr(obj({'checkId':H,'result':check,'reviewedEvidenceIds':arr(H),'outstandingVerificationSteps':arr(S)}),100000)})
ref=obj({'assessmentId':UUID,'assessmentHash':H,'execution':execution})
suppression=config['properties']['suppressions']['items']
row=obj({'scannerResult':check,'assessmentResult':nullable(check),'attestationResult':nullable(check),'effectiveResult':check,'conflicts':arr(S),'suppression':nullable(suppression)})
report=obj({'schemaVersion':en('1.0.0'),'reportId':UUID,'createdAt':D,'auditId':UUID,'auditHash':H,'assessmentRef':nullable(ref),'mode':en('static','assisted'),'execution':nullable(execution),'policyContext':policy,'scope':scope,'checks':arr(row,100000),'coverage':coverage,'summary':summary,'diagnostics':arr(diag,10000)})
auditref=obj({'auditId':UUID,'auditHash':H,'assessmentId':nullable(UUID),'assessmentHash':nullable(H)})
verification=obj({'schemaVersion':en('1.0.0'),'verificationId':UUID,'createdAt':D,'mode':en('static','assisted'),'baselineRef':auditref,'currentRef':auditref,'scopeComparison':en('same','different'),'versionComparison':en('same','different'),'policyComparison':en('same','different'),'items':arr(obj({'checkId':H,'previousResult':nullable(check),'currentResult':nullable(check),'classification':en('NOT_COMPARABLE','NEEDS_RECHECK','RESOLVED','CHANGED','UNCHANGED','NEW'),'direction':en('improved','worsened','neutral','unknown'),'reason':S}),100000),'summary':obj({'NOT_COMPARABLE':I,'NEEDS_RECHECK':I,'RESOLVED':I,'CHANGED':I,'UNCHANGED':I,'NEW':I,'newProblemCount':I,'changedProblemCount':I})})
for name,data in [('config',config),('audit',audit),('manifest',manifest),('assessment',assessment),('report',report),('verification',verification)]:
 data={'$schema':'https://json-schema.org/draft/2020-12/schema','$id':f'https://raw.githubusercontent.com/hamaup/smoothsubmit/main/schemas/{name}.schema.json',**data}
 Path(f'schemas/{name}.schema.json').write_text(json.dumps(data,indent=2)+'\n')
